### ISSUE TITLE
Cloud Pricing API image errors with "getaddrinfo ENOTFOUND"

### ISSUE THREAD

**Issue by aliscott** [infracost/helm-charts#18]
We've seen this error happen when deploying the Cloud Pricing API helm chart.

```
{"level":50,"time":1648498253526,"pid":62,"hostname":"cloud-pricing-api-init-job-vxbxz","msg":"There was an error downloading data: getaddrinfo ENOTFOUND pricing.api.infracost.io"}
```

This seems to be due to [DNS issues caused by alpine-based images](https://stackoverflow.com/questions/65181012/does-alpine-have-known-dns-issue-within-kubernetes/65593511#65593511).

A workaround for this is adding the following to your job and API pod definitions:
```yml
spec:
  ...
  template:
    ...
    spec:
      ...
      dnsConfig:
        options:
        - name: ndots
          value: "1"
 ```
